export class approve_hl{
    constructor(
      public lhis_id,
      public lhis_ps_id,
      public lhis_leave_id,
      public lhis_start_date,
      public lhis_end_date,
      public lhis_num_year,
      public lhis_num_day,
      public lhis_num_month,
      public lhis_budget_year,
      public lhis_address,
      public lhis_topic,
      public lhis_status_money,
      public lhis_less_money,
      public lhis_write_place,
      public lhis_write_date,
      public lhis_sub_topic,
      public lhis_leavet_id,
      public lhis_statususeleave,
      public lhis_place_name,
      public lhis_set_date,
      public lhis_place_name_2,
      public lhis_temple_1,
      public lhis_temple_2,
      public lhis_country_id,
      public lhis_capital,
      public lhis_conscription,
      public lhis_assignre_place,
      public lhis_gId,
      
      public lhis_status,
      public lhis_attach_file,
      public lhis_tell,
      public lhis_half_day_status,
      public leave_name,
      public ps_fname,
      public ps_lname,
      public pf_name,
      public apfp_dept_id,
      public apfp_seq,
      public apfp_opinion,
      public dept_name,
      public personId,
      public status_up
    ){}
  }